version: '3.8'

services:

  console:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      RUST_LOG: debug
    ports:
      - "8080:8080"
    command: [
      "--enable-private-ip",
      "--http-port", "8080", 
      "--sdn-port", "10000",
      "--sdn-zone-id", "0",
      "--sdn-zone-node-id", "0",
      "--workers", "2",
      "console"
      ]
      
  gateway:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      RUST_LOG: debug
    ports:
      - "3000:3000"
    depends_on:
      - console
    command: [
      "--enable-private-ip",
      "--http-port", "3000",
      "--sdn-port", "10001",
      "--sdn-zone-id", "0",
      "--sdn-zone-node-id", "1",
      "--seeds", "0@/ip4/127.0.0.1/udp/10000",
      "--workers", "2",
      "gateway",
      "--lat 10",
      "--lon 20",
      "--max-memory", "100",
      "--max-disk", "100",
      "--geo-db", "../maxminddb-data/GeoLite2-City.mmdb"
      ]

  media_n2:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      RUST_LOG: debug
    # ports:
      # - "8080:8080"
    depends_on:
      - console

    command: [
      "--enable-private-ip",
      "--sdn-zone-id", "0",
      "--sdn-zone-node-id", "2",
      "--seeds", "1@/ip4/127.0.0.1/udp/10000",
      "--workers", "2",
      "media",
      "--enable-token-api",
      ]

  media_n3:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      RUST_LOG: debug
    # ports:
      # - "8080:8080"
    depends_on:
      - console
    command: [
      "--enable-private-ip",
      "--sdn-zone-id", "0",
      "--sdn-zone-node-id", "3",
      "--seeds", "1@/ip4/127.0.0.1/udp/10000",
      "--workers", "2",
      "media",
      "--enable-token-api",
      ]

  connector:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      RUST_LOG: debug
    # ports:
      # - "8080:8080"
    depends_on:
      - console
    command: [
      "--enable-private-ip",
      "--sdn-zone-id", "0",
      "--sdn-zone-node-id", "1",
      "--seeds", "1@/ip4/127.0.0.1/udp/10000",
      "--workers", "2",
      "connector",
      "--s3-uri", "http://minioadmin:minioadmin@127.0.0.1:9000/record"
      ]
