version: '3.8'

x-common-variables: &common-variables
  network_mode: host
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    RUST_LOG: debug

services:
  console:
    <<: *common-variables
    entrypoint: ["/entrypoints/console.sh"]

  gateway:
    <<: *common-variables
    depends_on:
      - console
    entrypoint: ["/entrypoints/gateway.sh"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`demo-cluster.8xff.colligence.in`)"
      - "traefik.http.routers.gateway.service=gateway"
      - "traefik.http.routers.gateway.entrypoints=websecure"
      - "traefik.http.routers.gateway.tls.certresolver=letsencrypt"
      - "traefik.http.routers.gateway.tls.domains[0].main=atm0s.ds.colligence.in"
      - "traefik.http.services.gateway.loadbalancer.server.port=3000"

  media_n2:
    <<: *common-variables
    depends_on:
      - gateway
    entrypoint: ["/entrypoints/media.sh", "2"]

  media_n3:
    <<: *common-variables
    depends_on:
      - gateway
    entrypoint: ["/entrypoints/media.sh", "3"]

  connector:
    <<: *common-variables
    depends_on:
      - gateway
    entrypoint: ["/entrypoints/connector.sh"]

  traefik:
    image: traefik:v2.11
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/root/traefik.toml:/etc/traefik/traefik.toml"
      - "/root/acme.json:/acme.json"
    labels:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
